In [3]:
import pandas as pd
import numpy as np
import sqlite3

In [18]:
df1= pd.read_csv('C:\\Users\\Sunny Rai\\Downloads\\ChicagoCrimeData.csv')
df2= pd.read_csv('C:\\Users\\Sunny Rai\\Downloads\\ChicagoPublicSchools.csv')
df3= pd.read_csv('C:\\Users\\Sunny Rai\\Downloads\\ChicagoCensusData.csv')

In [26]:
df2.head(1)

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"

In [27]:
df3.head(1)

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0

In [28]:
df1.head(1)

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.80744,-87.703956,"(41.8074405, -87.703955849)"

In [2]:
import pandas as pd
import sqlite3


conn = sqlite3.connect("My_Project.db")


 #read csv file
df1 = pd.read_csv("C:\\Users\\Sunny Rai\\Downloads\\ChicagoCrimeData.csv")
df2 = pd.read_csv("C:\\Users\\Sunny Rai\\Downloads\\ChicagoPublicSchools.csv")
df3 = pd.read_csv("C:\\Users\\Sunny Rai\\Downloads\\ChicagoCensusData.csv")


df1.to_sql("crime_data", conn, if_exists="replace", index=False)
df2.to_sql("school_data", conn, if_exists="replace", index=False)
df3.to_sql("census_data", conn, if_exists="replace", index=False)

print("All 3 CSV files uploaded successfully!")

All 3 CSV files uploaded successfully!

In [55]:
query = """
SELECT *
FROM crime_data
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

print(result.head(3))

        ID CASE_NUMBER        DATE                     BLOCK IUCR  \
0  3512276    HK587712  2004-08-28        047XX S KEDZIE AVE  890
1  3406613    HK456306  2004-06-26  009XX N CENTRAL PARK AVE  820
2  8002131    HT233595  2011-04-04        043XX S WABASH AVE  820

  PRIMARY_TYPE     DESCRIPTION          LOCATION_DESCRIPTION  ARREST  \
0        THEFT   FROM BUILDING            SMALL RETAIL STORE       0
1        THEFT  $500 AND UNDER                         OTHER       0
2        THEFT  $500 AND UNDER  NURSING HOME/RETIREMENT HOME       0

   DOMESTIC  ...  DISTRICT  WARD  COMMUNITY_AREA_NUMBER  FBICODE X_COORDINATE  \
0         0  ...         9  14.0                   58.0        6    1155838.0
1         0  ...        11  27.0                   23.0        6    1152206.0
2         0  ...         2   3.0                   38.0        6    1177436.0

   Y_COORDINATE  YEAR   LATITUDE  LONGITUDE                       LOCATION
0     1873050.0  2004  41.807440 -87.703956    (41.8074405, -87.703955849)
1     1906127.0  2004  41.898280 -87.716406  (41.898279962, -87.716405505)
2     1876313.0  2011  41.815933 -87.624642  (41.815933131, -87.624642127)

[3 rows x 21 columns]

In [56]:
query = """
SELECT count(*) as total_rows
FROM crime_data;
"""

result = pd.read_sql_query(query, conn)

print(result.head(3))

   total_rows
0         533

In [58]:
query = """ select count(*) as total_rows from school_data;"""

result = pd.read_sql_query(query, conn)

print(result)

   total_rows
0         566

In [59]:
query = """ select count(*) as total_rows from census_data;"""

result = pd.read_sql_query(query , conn)
print(result)

   total_rows
0          78

In [3]:
query = """
SELECT community_area_name, community_area_number, per_capita_income
FROM census_data
WHERE per_capita_income < 11000;
"""       

result = pd.read_sql_query(query, conn)

print(result.to_string(index=False))

COMMUNITY_AREA_NAME  COMMUNITY_AREA_NUMBER  PER_CAPITA_INCOME
 West Garfield Park                   26.0              10934
     South Lawndale                   30.0              10402
        Fuller Park                   37.0              10432
          Riverdale                   54.0               8201

In [ ]:
#List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis) 

query = """ select case_number from crime_data 
where description like '%MINOR%'
or description not like '%CHILD%' """

result = pd.read_sql_query(query , conn)

print(result.to_string(index=False))

CASE_NUMBER
   HK587712
   HK456306
   HT233595
   HT133522
   HZ138551
   HS540106
   HZ534771
   HL793243
   HL149610
   HK361551
   HX552797
   HT180228
   HV243612
   HN200365
   HK108680
   HY396729
   HR271603
   HX332132
   HW303994
   HS569246
   HY234744
   HP320451
   HN484464
   JB151690
   HR582990
   HR535632
   HH486939
   HW441620
   HJ561433
   HR583513
   HX509438
   HS681158
   HK350670
    G256545
   JA272438
   HH201585
    G212935
   HL590300
   HL409680
   HM324025
    G662598
   HV353560
   HR261581
   HL680775
   HM543491
   HY167451
   HY377901
   HX225704
   HJ308632
   HV528008
   HK801112
   HS532107
   JA261898
   JA559176
   JA412895
   HY273740
   HZ224258
   HJ652747
    G040244
   HJ415128
   HV534721
   JA503725
   HM803061
   HN731220
   HP691879
   HV537004
   HR149903
   HX314361
   HV345270
   HS308747
   HK728309
   HL005270
   HY291329
   HJ678713
   HY412959
   HX155070
   HV402967
   HX332979
   HJ710634
   HX165034
   HR385117
   HS230912
   HL177398
   HH702524
   JA384163
   HJ672058
   HT368471
   HY202462
   HX354359
   HZ146741
    G376790
   HX262353
   HP317516
   HZ335434
   HS678732
   HL382289
   HM392612
   HH869886
   HR460350
   HM117889
   HR576816
   HZ372381
   HZ556726
   HN421595
   HK454598
   HH657809
   HS451246
   HH316735
    G597730
    G736811
   HT651635
   HZ432273
    G517474
   HP746347
    G056330
   HN772519
   HZ309936
   HY368284
   HL353697
   HT375934
   JA188596
   HL725506
   HV395700
   HH696901
   HT390647
   HK815196
   JA490957
   HK103473
   HM556695
   HH558381
   HK498590
   HX455839
   HR703960
   HL646682
   HV445580
    G688026
   HJ466766
   HL632721
   HP579910
   HL718742
   HP714065
   HP716225
   HW481295
   HS568476
   JB213238
   HS475732
   HS595785
   HR408597
   HT542713
   HL240985
   HJ254782
   HK561262
   HW213573
    G419948
   HL177008
   HJ639869
   HM217017
   HL388623
   HY189363
   HS498285
   HN224900
   HR387668
   HJ294892
   HL745027
    G533278
   HH827769
   HH639427
   HK771992
   HH867007
   HJ575773
   HR136920
   HT457930
    G070193
   HJ724585
   HP121474
    G198370
   HJ723825
   HJ458342
   HP558812
   HY192694
   HN472326
   HK756778
   HH741961
   JA460432
    G140454
   HX239866
   HM378171
   HW182288
   HZ295843
   HM673431
   HP352546
   HR286405
   HR195987
   HW261668
   JA496716
   JA344492
   HZ334220
   HR217367
   HV268964
   JA483294
   HT169840
   HT621306
   HS269736
   HK243330
   HH262924
   HL613433
   HY267896
   HN568531
   HT112422
   HV479133
   HV592346
   HH619797
   HZ376709
   HV573337
   HL269210
   HL567458
   HR674429
   HM200888
   HX467661
   HX448587
   HS200939
   HN335611
   HZ535494
   HX154767
   HM337445
   HM244120
   HR342598
   HL187666
   HW449676
   HS589302
   HX145326
   HN553354
   HN784049
   HJ527694
   HM303461
   HM535632
   HT353855
    G134016
   HR125162
    G496261
   HJ842548
   HN280980
   JA560123
   HY405637
   HP689703
   HR345366
   HZ242802
   HM661326
   HJ336995
   HK694552
   HJ760939
   HV366181
   HJ563089
   HH576932
   HR308948
   HK100758
   HV328581
   HV267193
   HJ620738
   HJ557529
   HS498920
   HL608698
    G323273
   HK577020
   HY365876
   HS305355
   HK162357
   HN778969
   HV185969
   HH657604
   HW555338
   HV268708
    G170513
   HW160463
   HN355411
   HK190723
   HV457847
   HW566855
   HL141298
   HR281750
   HL342355
   HX112183
   HJ624999
   HJ618818
   HR597126
   HN558484
   HR505781
   HN522324
   HN647052
   HT323138
   HW562748
   HN719188
   HT237921
   HY215032
   HK369511
   HL703172
   HM762800
   HN370211
   HR195962
   HM284854
   HL319228
   HR447925
   HM590293
   HP513177
   HL331611
   HN448271
   HH402660
   HN422493
   HP263901
    G577663
   HT535175
   JA110097
   HM360756
   HN275969
   HZ544441
   HL660560
   HS164946
   HR399710
   HP243837
   HP157774
   HP340132
   HJ388435
   JA246453
   HN407116
   JA107722
   HJ532105
   HH729144
   HY204891
   HZ228967
   HY385205
   HK328402
   JA349450
   HK743113
   HR185873
   HH692211
   JA470839
   HY182950
   HR668156
   HZ234518
   HW569852
   HS314108
   HH463517
   HN182437
   HW493063
   HJ637197
   HH829588
   HZ322965
   HW415978
   HL315870
   HJ222529
   HM535930
   HZ242203
   HN213069
   HH343366
   JA269772
   HH106347
   HM507529
   HP258815
   HL111533
   HS479338
   HZ403432
   HV462975
   HW414519
   HL414306
   HT315369
   HL330223
   HK751265
   HT540548
   HX398190
   HK348713
   HR206683
   HH154448
   JA462321
   HV233824
   HR307075
   HZ134318
   HM437597
   HW233866
    G659211
   HW274134
   HW526270
    G375927
   HP325677
   HL300450
   HN246122
   HH149573
   HK450946
   HT434553
   HL548996
   HR696852
   HK481967
   HT202584
   HJ409442
   HT251336
   HV575905
   HR489129
   HT427568
   HR539548
   HS426544
   HT556032
   HL254965
   JA216127
   HW350078
   HR308245
   HY455377
   HP747058
   HN645348
   HL334216
   HS230740
   HV593288
   HK341632
   HH859922
    G611731
   HM757133
   HJ786817
   HV356669
   HX207970
   HM733422
   HH352862
    G652158
   HX301095
   HY163644
   HR140766
   HH605275
   HJ513676
   HH337319
   HH423186
   HN543219
   HZ463811
   HN702776
   HR607189
    G654957
   HL131736
   HN519755
    G629024
   HL239939
   HK328522
   HJ349966
    G345035
   JA394755
   HY518743
   JA550741
   HH493814
   HZ523997
    G161722
   HY455698
   HH208082
   HT404945
   HL213843
   HM422467
   JA192460
   HL446401
   HS330202
   HP661088
   HJ281736
   HN136243
   HJ580490
   HV213648
   HV514287
   HJ753917
   JA133264
   HJ642080
   JA557966
   HV548880
   HR480844
   HW568748
   HH405177
   HL472862
    G326063
   HL424420
   JA393243
   HR585012
   JA455629
   HV369974
   HN637742
   HW557360
   HJ776916
   HJ419340
   HH329720
   HM802052
   HJ804627
   HR190881
    G575031
    G122095
   HN595319
    G302291
    G057394
   HM590468
   HV463112
   HK749575
   HS100098
   HW576249
   HK485601
   HH460583
   HM576559
   HL611297
   HV356389
   HX203242
   HH292682
    G635735
   HM768251
   HT394616
   HH688935
   HK677648
    G158614
   HK310265
   HR314298
   HT404326
   HY259084
   HL415544
   HP265256
   HR392537
   HL266884
   HK238408
   HX343113
   HM195342
   HW519443
   JA359626
   HN544458
   HW238778
   JB155558
   HY458571
   HZ378869
   HZ378355
   HX258445
   HZ192829
   HZ133234
   HJ747227
   JA143710
    G021609